
// RobotBuilder Version: 3.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot.subsystems;


import frc.robot.Constants;
import frc.robot.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.motorcontrol.Spark;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class Climbing extends SubsystemBase {
    private Spark middleHook;
    private Spark leftHook;
    private Spark rightHook;
    private DigitalInput backLimitSwitch;
    private DigitalInput frontLimitSwitch;
        
    public Climbing() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        middleHook = new Spark(Constants.ClimbConstants.slidingPort);
        leftHook =  new Spark(Constants.ClimbConstants.leftHook);
        rightHook = new Spark(Constants.ClimbConstants.rightHook);
        backLimitSwitch = new DigitalInput(Constants.ClimbConstants.leftLSPort);
        frontLimitSwitch= new DigitalInput(Constants.ClimbConstants.rightLSPort);
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run
        if(backLimitSwitch.get() && middleHook.get() < 0 || frontLimitSwitch.get() && middleHook.get() > 0){
            middleHook.set(0);
        }
    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void setSlidingSpeed(double speed){
        if(backLimitSwitch.get() && speed < 0 || frontLimitSwitch.get() && speed > 0){
            middleHook.set(0);
        }else{
            middleHook.set(speed);
        }
    } 

    public void setLeftHookSpeed(double speed){
        leftHook.set(speed);
    }

    public void setRightHookSpeed(double speed){
        rightHook.set(speed);
    }
}
